### ISSUE TITLE
Auto language based on user browser language preference

### ISSUE THREAD

**Issue by Tintels** [isaachinman/wundershine-web-app#28]
**Describe the bug**
I think the automatic detection and redirect is not working. 

**To Reproduce**
1. Set browser language preference to Dutch
2. Go to www.wundershine.com or www.wundershine.com/creative

**Expected behavior**
Automatic redirect to www.wundershine.com/nl and www.wundershine.com/nl/creative respectively

**Browser (please complete the following information):**
 - Device: Windows 10 laptop
 - Browser: Edge

**Additional context**' 
I have implemented the Weglot app for Shopify. There is a feature for "Automatically switch to the visitors' preferred language" When I was testing that, I noticed that auto switching does work for our shop, but not for our landing website pages. 

This Weglot auto switch feature by the way is not part of the free plan. It is working for another 4 days because we are on a free trail plan now. I hope we can avoid an additional 9,90 EUR pm or the time being:

https://weglot.com/pricing/

I will create an issue request here for linking to the correct langauge shop if possible.

**Comment by isaachinman** [comment]
This is not a bug. There is no redirect, that's why we have different URLs in the first place.

If a user wants Dutch, they should be directed to the `/nl/` route.

The assumption is that the route takes preference over the browser language.

Or, to put it a different way, `www.wundershine.com` is an English page only. Likewise, `www.wundershine.com/nl` is a Dutch page only.

You're saying you want this to change?

**Comment by Tintels** [comment]
Yes, it would be great if the user can be redirected to the preferred language version .

**Comment by isaachinman** [comment]
And how do we determine the "preferred language version"? It's always the browser language?

**Comment by Tintels** [comment]
Yes please. 

It would be consistent with Weglot on our store if we go for a non-free plan. Point 4 here:
https://blog.weglot.com/5-tips-to-make-multilingual-website-more-user-friendly/

**Comment by isaachinman** [comment]
Of course we are already automatically detecting user language. I just assumed that if a user is in a non-English language and hits `www.wundershine.com` instead of `www.wundershine.com/nl`, it's because they want to see English. Search engines in Dutch should automatically point to the `/nl` version.

**Comment by isaachinman** [comment]
8add3ff

**Comment by Tintels** [comment]
I get a bit of unexpected behaviour. Will test more and close the issue or post more here.

**Comment by isaachinman** [comment]
@Tintels Any update on that unexpected behaviour?

**Comment by Tintels** [comment]
Happy New Year!

Tests are a bit tricky due to (syncing) account and browser preferences, but after more tests, the redirect to NL does behave as expected after all. A user preference override to English also does seems to be remembered by cookie. That is good.
